name = "NFFT3"
uuid = "53104703-03e8-40a5-ab01-812303a44cae"
authors = ["Michael Schmischke <michael.schmischke@math.tu-chemnitz.de> for the julia package and other contributors for the NFFT (see nfft.org)"]
version = "1.1"

[compat]
julia = "1"
