name = "NFFT3"
uuid = "53104703-03e8-40a5-ab01-812303a44cae"
authors = ["Michael Schmischke <michael.schmischke@math.tu-chemnitz.de> for the julia package and other contributors for the NFFT (see nfft.org)"]
version = "1.2.1"

[deps]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CpuId = "adafc99b-e345-5852-983c-f28acb93d879"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Aqua = "0.5 - 0.8"
CpuId = "0.3"
LinearAlgebra = "1"
Test = "1"
julia = "1"
